### ISSUE TITLE
Link not wroking

### ISSUE THREAD

**Issue by MaxSustainableSolutions** [karamba3d/K3D_tests#2]
Hi, 

I tried to run the project, but the link to karamba.dll and karambaCommon.dll is offline. Is there another place where I can get the dll's? 

Kind Regards,
Max

**Comment by karamba3d** [comment]
Hi Max,
sorry for my late reply. My notification settings were not correct. I updated the repo to Karamba3D 2.0.0 and the link is not necessary any more.
-- Clemens

**Comment by MaxSustainableSolutions** [comment]
Hi Clemens,

Thanks, yes figured that out and got it working inside visual studio. I am
currently working on a plugin to analyse modular timber construction. But I
have another question regard the scripting with Karamba: Is it possible in
the future to create line connections with a stiffness?

Kind regards,
Max

Op wo 27 jan. 2021 om 11:05 schreef Karamba3D <notifications@github.com>:

**Comment by karamba3d** [comment]
Hi Max,
with version 2.0.0 it is possible to specify line joints which have a stiffness. The functionality is already there and can be tested (see https://github.com/karamba3d/K3D_NightlyBuilds/releases).

Take a look at the updated unit-tests project (https://github.com/karamba3d/K3D_tests). There is a deactivated test in the folder 'Joints' which shows how it works. The test is deactivated because I am still working on it: the static condensation procedure used results in unprecise results for natural vibrations and buckling calculations in case of beam calculations.

I hope to have it within the next one ore two weeks.

[https://avatars3.githubusercontent.com/u/30176575?s=400&v=4]<https://github.com/karamba3d/K3D_NightlyBuilds/releases>
Releases · karamba3d/K3D_NightlyBuilds · GitHub<https://github.com/karamba3d/K3D_NightlyBuilds/releases>
NightlyBuilds version of Karamba3d . Contribute to karamba3d/K3D_NightlyBuilds development by creating an account on GitHub.
github.com

best,
Clemens
cp@karamba3d.com<mailto:cp@karamba3d.com>


Karamba3D
Clemens Preisinger
A-1010 Vienna
www.karamba3d.com<https://www.karamba3d.com>
LinkedIn<https://www.linkedin.com/company/karamba3d> | Instagram<https://www.instagram.com/karamba3d/> | Youtube<https://www.youtube.com/c/karamba3d>


________________________________

**Comment by MaxSustainableSolutions** [comment]
Hi Clemens,

The nightly build works like a charm. I faced another problem by modelling
the timber structure regard the non-linear springs (See figures), haven't
found an option yet in Karamba to implement this. A workaround would be to
implement an iterative process and indicate the compression/tension points.
Do you have another suggestion to solve this problem?

Kind regards,
Max

[image: image.png]
[image: image.png]


Op di 2 feb. 2021 om 09:59 schreef Karamba3D <notifications@github.com>:

**Comment by karamba3d** [comment]
Hi Max,
non-linear joint stiffness is not yet implemented in Karamba3D 2.0.0
It could be done like you indicate.
In order to get reliable convergence and correct results it is necessary to implement an incremental iterative procedure which can not be easily implemented in from C# with the C++ api currently available for the Karamba3D calculation core.

best,
Clemens
cp@karamba3d.com<mailto:cp@karamba3d.com>


Karamba3D
Clemens Preisinger
A-1010 Vienna
www.karamba3d.com<https://www.karamba3d.com>
LinkedIn<https://www.linkedin.com/company/karamba3d> | Instagram<https://www.instagram.com/karamba3d/> | Youtube<https://www.youtube.com/c/karamba3d>


________________________________
